#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/taimen

PRODUCT_COPY_FILES += \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/airtel_in.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/airtel_in.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/apt_tw.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/apt_tw.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/att5g_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/att5g_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/att_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/att_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/bell_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/bell_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/bluegrass_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/bluegrass_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/boost_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/boost_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/bouygues_fr.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/bouygues_fr.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/btb_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/btb_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/btc_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/btc_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/carrier_list.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/carrier_list.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/cellcom_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/cellcom_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/cht_tw.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/cht_tw.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/congstar_de.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/congstar_de.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/cricket5g_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/cricket5g_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/cricket_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/cricket_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/cspire_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/cspire_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/default.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/default.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/docomo_jp.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/docomo_jp.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/ee_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/ee_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/eplus_de.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/eplus_de.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/esn_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/esn_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/fet_tw.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/fet_tw.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/fi_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/fi_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/fido_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/fido_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/firstnet_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/firstnet_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/firstnetpacific_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/firstnetpacific_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/fizz_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/fizz_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/freedommobile_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/freedommobile_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/h3_at.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/h3_at.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/h3_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/h3_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/h3_se.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/h3_se.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/idea_in.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/idea_in.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/idmobile_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/idmobile_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/kddi_jp.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/kddi_jp.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/kddimvno_jp.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/kddimvno_jp.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/koodo_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/koodo_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/luckymobile_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/luckymobile_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/movistar_es.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/movistar_es.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/o2_de.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/o2_de.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/o2postpaid_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/o2postpaid_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/o2prepaid_de.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/o2prepaid_de.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/o2prepaid_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/o2prepaid_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/optus_au.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/optus_au.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/orange_es.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/orange_es.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/orange_fr.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/orange_fr.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/others.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/others.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/pcmobilebell_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/pcmobilebell_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/rakuten_jp.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/rakuten_jp.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/rjio_in.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/rjio_in.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/rogers_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/rogers_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/sfr_fr.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/sfr_fr.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/shaw_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/shaw_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/simple_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/simple_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/singtel_sg.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/singtel_sg.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/smarty_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/smarty_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/softbank_jp.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/softbank_jp.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/solomobile_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/solomobile_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/spectrum_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/spectrum_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/sprint_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/sprint_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/sprintprepaid_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/sprintprepaid_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/sprintwholesale_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/sprintwholesale_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/starhub_sg.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/starhub_sg.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/swisscom_ch.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/swisscom_ch.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/swisscom_li.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/swisscom_li.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/tbaytel_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/tbaytel_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/tdc_dk.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/tdc_dk.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/tele2_se.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/tele2_se.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/telekom_de.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/telekom_de.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/telenor_dk.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/telenor_dk.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/telenor_no.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/telenor_no.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/telenor_se.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/telenor_se.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/telia_no.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/telia_no.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/telia_se.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/telia_se.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/telstra_au.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/telstra_au.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/telus_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/telus_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/three_dk.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/three_dk.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/tim_it.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/tim_it.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/tmobile_nl.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/tmobile_nl.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/tmobile_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/tmobile_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/tracfonetmo_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/tracfonetmo_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/tracfoneverizon_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/tracfoneverizon_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/tstar_tw.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/tstar_tw.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/twm_tw.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/twm_tw.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/uscc_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/uscc_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/verizon_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/verizon_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/videotron_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/videotron_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/virgin_ca.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/virgin_ca.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/virgin_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/virgin_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/visible_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/visible_us.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/vodafone_au.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/vodafone_au.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/vodafone_de.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/vodafone_de.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/vodafone_es.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/vodafone_es.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/vodafone_gb.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/vodafone_gb.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/vodafone_ie.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/vodafone_ie.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/vodafone_in.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/vodafone_in.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/vodafone_it.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/vodafone_it.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/vodafone_nl.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/vodafone_nl.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/vodafone_tr.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/vodafone_tr.pb \
    vendor/google/taimen/proprietary/product/etc/CarrierSettings/xfinity_us.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/xfinity_us.pb \
    vendor/google/taimen/proprietary/product/etc/ambient/matcher_tah.leveldb:$(TARGET_COPY_OUT_PRODUCT)/etc/ambient/matcher_tah.leveldb \
    vendor/google/taimen/proprietary/product/etc/permissions/com.android.omadm.service.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.android.omadm.service.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/com.android.sdm.plugins.connmo.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.android.sdm.plugins.connmo.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/com.android.sdm.plugins.dcmo.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.android.sdm.plugins.dcmo.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/com.android.sdm.plugins.diagmon.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.android.sdm.plugins.diagmon.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/com.android.sdm.plugins.sprintdm.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.android.sdm.plugins.sprintdm.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/com.google.android.hardwareinfo.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.google.android.hardwareinfo.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/com.verizon.apn.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.verizon.apn.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/com.verizon.services.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.verizon.services.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/features-verizon.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/features-verizon.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/obdm_permissions.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/obdm_permissions.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/privapp-permissions-google-p.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-google-p.xml \
    vendor/google/taimen/proprietary/product/etc/permissions/vzw_mvs_permissions.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/vzw_mvs_permissions.xml \
    vendor/google/taimen/proprietary/product/etc/sysconfig/google-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google-hiddenapi-package-whitelist.xml \
    vendor/google/taimen/proprietary/product/etc/sysconfig/nexus.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/nexus.xml \
    vendor/google/taimen/proprietary/product/etc/sysconfig/pixel_experience_2017.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/pixel_experience_2017.xml \
    vendor/google/taimen/proprietary/product/etc/sysconfig/whitelist_com.android.omadm.service.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/whitelist_com.android.omadm.service.xml \
    vendor/google/taimen/proprietary/system/etc/cne/Nexus/ATT/ATT_profiles.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/cne/Nexus/ATT/ATT_profiles.xml \
    vendor/google/taimen/proprietary/system/etc/cne/Nexus/ROW/ROW_profiles.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/cne/Nexus/ROW/ROW_profiles.xml \
    vendor/google/taimen/proprietary/system/etc/cne/Nexus/VZW/VZW_profiles.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/cne/Nexus/VZW/VZW_profiles.xml \
    vendor/google/taimen/proprietary/system/etc/firmware/dnd.descriptor:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dnd.descriptor \
    vendor/google/taimen/proprietary/system/etc/firmware/dnd.sound_model:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/dnd.sound_model \
    vendor/google/taimen/proprietary/system/etc/firmware/music_detector.descriptor:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/music_detector.descriptor \
    vendor/google/taimen/proprietary/system/etc/firmware/music_detector.sound_model:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/music_detector.sound_model \
    vendor/google/taimen/proprietary/system/etc/permissions/com.google.android.camera.experimental2017.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.google.android.camera.experimental2017.xml \
    vendor/google/taimen/proprietary/system/etc/permissions/com.verizon.embms.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.verizon.embms.xml \
    vendor/google/taimen/proprietary/system/etc/permissions/privapp-permissions-aosp_wahoo.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-aosp_wahoo.xml \
    vendor/google/taimen/proprietary/system/etc/permissions/privapp-permissions-google.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-google.xml \
    vendor/google/taimen/proprietary/system/etc/permissions/privapp-permissions-wahoo.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-wahoo.xml \
    vendor/google/taimen/proprietary/system/etc/sysconfig/pixel_2017_exclusive.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/pixel_2017_exclusive.xml \
    vendor/google/taimen/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/google/taimen/proprietary/system_ext/etc/permissions/com.android.omadm.radioconfig.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.omadm.radioconfig.xml \
    vendor/google/taimen/proprietary/system_ext/etc/permissions/privapp-permissions-google-se.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-google-se.xml

PRODUCT_PACKAGES += \
    com.qualcomm.qti.imsrtpservice@1.0 \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libimscamera_jni \
    libimsmedia_jni \
    librcc \
    libdmengine \
    libdmjavaplugin \
    libakuaf \
    libmotricity \
    QAS_DVC_MSP_VZW \
    ims \
    uceShimService \
    vzw_msdc_api \
    CNEService \
    OemDmTrigger \
    qcrilmsgtunnel \
    VZWAPNLib \
    AmbientSensePrebuilt \
    AppDirectedSMSService \
    CarrierServices \
    CarrierSettings \
    CarrierWifi \
    ConnMO \
    DCMO \
    DMService \
    DevicePersonalizationPrebuiltPixel2 \
    DiagMon \
    HardwareInfo \
    HotwordEnrollmentOKGoogleWCD9340 \
    HotwordEnrollmentXGoogleWCD9340 \
    MyVerizonServices \
    OBDM_Permissions \
    SprintDM \
    SprintHM \
    TetheringEntitlement \
    WfcActivation \
    obdm_stub \
    CarrierSetup \
    cneapiclient \
    com.google.android.camera.experimental2017 \
    com.quicinc.cne.api-V1.0-java \
    com.quicinc.cne \
    qcrilhook \
    rcsimssettings \
    vendor.qti.qcril.am-V1.0-java \
    libhwinfo \
    RadioConfigLib \
    com.android.hotwordenrollment.common.util \
    move_widevine_data

PRODUCT_PACKAGES += \
    product_priv-app_DMService_lib_arm_libdmengine_so \
    product_priv-app_DMService_lib_arm_libdmjavaplugin_so \
    product_priv-app_MyVerizonServices_lib_arm64_libakuaf_so \
    product_priv-app_MyVerizonServices_lib_arm64_libmotricity_so \
    system_app_ims_lib_arm64_libimscamera_jni_so \
    system_app_ims_lib_arm64_libimsmedia_jni_so

PRODUCT_COPY_FILES += \
    vendor/google/taimen/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/google/taimen/proprietary/vendor/etc/acdbdata/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Codec_cal.acdb \
    vendor/google/taimen/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/google/taimen/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/google/taimen/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/google/taimen/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/google/taimen/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/google/taimen/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/google/taimen/proprietary/vendor/etc/acdbdata/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/workspaceFile.qwsp \
    vendor/google/taimen/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/google/taimen/proprietary/vendor/etc/camera/imx179_pixel_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx179_pixel_chromatix.xml \
    vendor/google/taimen/proprietary/vendor/etc/camera/imx362_pixel_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx362_pixel_chromatix.xml \
    vendor/google/taimen/proprietary/vendor/etc/chre/preloaded_nanoapps.json:$(TARGET_COPY_OUT_VENDOR)/etc/chre/preloaded_nanoapps.json \
    vendor/google/taimen/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/google/taimen/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/google/taimen/proprietary/vendor/etc/flp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/flp.conf \
    vendor/google/taimen/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.2-service.fpc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.2-service.fpc.rc \
    vendor/google/taimen/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/google/taimen/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/google/taimen/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/google/taimen/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/google/taimen/proprietary/vendor/etc/init/android.hardware.oemlock@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.oemlock@1.0-service.rc \
    vendor/google/taimen/proprietary/vendor/etc/init/init-ramoops.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-ramoops.rc \
    vendor/google/taimen/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/google/taimen/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/google/taimen/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/google/taimen/proprietary/vendor/etc/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile0.conf \
    vendor/google/taimen/proprietary/vendor/etc/permissions/cneapiclient.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/cneapiclient.xml \
    vendor/google/taimen/proprietary/vendor/etc/permissions/com.quicinc.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.quicinc.cne.xml \
    vendor/google/taimen/proprietary/vendor/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qcrilhook.xml \
    vendor/google/taimen/proprietary/vendor/etc/permissions/qti-vzw-ims-internal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qti-vzw-ims-internal.xml \
    vendor/google/taimen/proprietary/vendor/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/telephonyservice.xml \
    vendor/google/taimen/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/google/taimen/proprietary/vendor/etc/qdcm_calib_data_SW43402_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_SW43402_cmd_mode_dsc_dsi_panel.xml \
    vendor/google/taimen/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/google/taimen/proprietary/vendor/etc/sensors/sensor_def_wahoo.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_wahoo.conf \
    vendor/google/taimen/proprietary/vendor/firmware/Data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/Data.msc \
    vendor/google/taimen/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/google/taimen/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/google/taimen/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/google/taimen/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/google/taimen/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/google/taimen/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/google/taimen/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/google/taimen/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/google/taimen/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/google/taimen/proprietary/vendor/firmware/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b00 \
    vendor/google/taimen/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    vendor/google/taimen/proprietary/vendor/firmware/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b02 \
    vendor/google/taimen/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    vendor/google/taimen/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b00 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b01 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b02 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b03 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b04 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b05 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b06 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b08 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b09 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b11 \
    vendor/google/taimen/proprietary/vendor/firmware/adsp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.mdt \
    vendor/google/taimen/proprietary/vendor/firmware/bdwlan.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b09 \
    vendor/google/taimen/proprietary/vendor/firmware/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.bin \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b01 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b03 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b05 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b06 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b07 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b09 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b11 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b13 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b15 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b16 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b18 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b20 \
    vendor/google/taimen/proprietary/vendor/firmware/cpe_9340.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.mdt \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b00 \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b01 \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b02 \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b03 \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b04 \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b05 \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b06 \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b07 \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.mbn \
    vendor/google/taimen/proprietary/vendor/firmware/cppf.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.mdt \
    vendor/google/taimen/proprietary/vendor/firmware/crbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw21.tlv \
    vendor/google/taimen/proprietary/vendor/firmware/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv21.bin \
    vendor/google/taimen/proprietary/vendor/firmware/drv2624.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/drv2624.bin \
    vendor/google/taimen/proprietary/vendor/firmware/easel/Image:$(TARGET_COPY_OUT_VENDOR)/firmware/easel/Image \
    vendor/google/taimen/proprietary/vendor/firmware/easel/fip.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/easel/fip.bin \
    vendor/google/taimen/proprietary/vendor/firmware/easel/mnh.dtb:$(TARGET_COPY_OUT_VENDOR)/firmware/easel/mnh.dtb \
    vendor/google/taimen/proprietary/vendor/firmware/easel/ramdisk.img:$(TARGET_COPY_OUT_VENDOR)/firmware/easel/ramdisk.img \
    vendor/google/taimen/proprietary/vendor/firmware/ese/prodkeys/ese.f000.prodkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/prodkeys/ese.f000.prodkeys \
    vendor/google/taimen/proprietary/vendor/firmware/ese/prodkeys/ese.f102.prodkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/prodkeys/ese.f102.prodkeys \
    vendor/google/taimen/proprietary/vendor/firmware/ese/prodkeys/ese.f200.prodkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/prodkeys/ese.f200.prodkeys \
    vendor/google/taimen/proprietary/vendor/firmware/ese/prodkeys/ese.f201.prodkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/prodkeys/ese.f201.prodkeys \
    vendor/google/taimen/proprietary/vendor/firmware/ese/prodkeys/ese.shadata.prodkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/prodkeys/ese.shadata.prodkeys \
    vendor/google/taimen/proprietary/vendor/firmware/ese/testkeys/ese.f000.testkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/testkeys/ese.f000.testkeys \
    vendor/google/taimen/proprietary/vendor/firmware/ese/testkeys/ese.f102.testkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/testkeys/ese.f102.testkeys \
    vendor/google/taimen/proprietary/vendor/firmware/ese/testkeys/ese.f200.testkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/testkeys/ese.f200.testkeys \
    vendor/google/taimen/proprietary/vendor/firmware/ese/testkeys/ese.f201.testkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/testkeys/ese.f201.testkeys \
    vendor/google/taimen/proprietary/vendor/firmware/ese/testkeys/ese.shadata.testkeys:$(TARGET_COPY_OUT_VENDOR)/firmware/ese/testkeys/ese.shadata.testkeys \
    vendor/google/taimen/proprietary/vendor/firmware/fpctzappfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b00 \
    vendor/google/taimen/proprietary/vendor/firmware/fpctzappfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b01 \
    vendor/google/taimen/proprietary/vendor/firmware/fpctzappfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b02 \
    vendor/google/taimen/proprietary/vendor/firmware/fpctzappfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b03 \
    vendor/google/taimen/proprietary/vendor/firmware/fpctzappfingerprint.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b04 \
    vendor/google/taimen/proprietary/vendor/firmware/fpctzappfingerprint.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b05 \
    vendor/google/taimen/proprietary/vendor/firmware/fpctzappfingerprint.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b06 \
    vendor/google/taimen/proprietary/vendor/firmware/fpctzappfingerprint.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b07 \
    vendor/google/taimen/proprietary/vendor/firmware/fpctzappfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.mdt \
    vendor/google/taimen/proprietary/vendor/firmware/ftm4_fw.ftb:$(TARGET_COPY_OUT_VENDOR)/firmware/ftm4_fw.ftb \
    vendor/google/taimen/proprietary/vendor/firmware/ftm4_fw_evt1.ftb:$(TARGET_COPY_OUT_VENDOR)/firmware/ftm4_fw_evt1.ftb \
    vendor/google/taimen/proprietary/vendor/firmware/ftm4_fw_lb.ftb:$(TARGET_COPY_OUT_VENDOR)/firmware/ftm4_fw_lb.ftb \
    vendor/google/taimen/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/google/taimen/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/google/taimen/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/google/taimen/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/google/taimen/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/google/taimen/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/google/taimen/proprietary/vendor/firmware/modemuw.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/modemuw.jsn \
    vendor/google/taimen/proprietary/vendor/firmware/nanoapp_config.textproto:$(TARGET_COPY_OUT_VENDOR)/firmware/nanoapp_config.textproto \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b00 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b01 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b02 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b03 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b04 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b05 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b06 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b07 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b08 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b09 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b10 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b11 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b12 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b13 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.b14 \
    vendor/google/taimen/proprietary/vendor/firmware/slpi_v2.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi_v2.mdt \
    vendor/google/taimen/proprietary/vendor/firmware/tas2557s_PG21_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2557s_PG21_uCDSP.bin \
    vendor/google/taimen/proprietary/vendor/firmware/tas2557s_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2557s_uCDSP.bin \
    vendor/google/taimen/proprietary/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    vendor/google/taimen/proprietary/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    vendor/google/taimen/proprietary/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    vendor/google/taimen/proprietary/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    vendor/google/taimen/proprietary/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    vendor/google/taimen/proprietary/vendor/firmware/venus.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mbn \
    vendor/google/taimen/proprietary/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00 \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01 \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02 \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03 \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b04 \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b05 \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b06 \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b07 \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mbn \
    vendor/google/taimen/proprietary/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt \
    vendor/google/taimen/proprietary/vendor/firmware/wlanmdsp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/wlanmdsp.mbn \
    vendor/google/taimen/proprietary/vendor/lib/dsp/CFCMModule.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/CFCMModule.so.1 \
    vendor/google/taimen/proprietary/vendor/lib/dsp/EtsiAmrWbPlusDecModule.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/EtsiAmrWbPlusDecModule.so.1 \
    vendor/google/taimen/proprietary/vendor/lib/dsp/EtsiEaacPlusEncAndCmnModule.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/EtsiEaacPlusEncAndCmnModule.so.1 \
    vendor/google/taimen/proprietary/vendor/lib/dsp/HeaacDecoderModule.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/HeaacDecoderModule.so.1 \
    vendor/google/taimen/proprietary/vendor/lib/dsp/HpMp2DecoderModule.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/HpMp2DecoderModule.so.1 \
    vendor/google/taimen/proprietary/vendor/lib/dsp/SAPlusCmnModule.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/SAPlusCmnModule.so.1 \
    vendor/google/taimen/proprietary/vendor/lib/dsp/activity.napp_header:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/activity.napp_header \
    vendor/google/taimen/proprietary/vendor/lib/dsp/cc.napp_header:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/cc.napp_header \
    vendor/google/taimen/proprietary/vendor/lib/dsp/elmyra.napp_header:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/elmyra.napp_header \
    vendor/google/taimen/proprietary/vendor/lib/dsp/fastrpc_shell_0:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/fastrpc_shell_0 \
    vendor/google/taimen/proprietary/vendor/lib/dsp/fluence_voiceplus_module.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/fluence_voiceplus_module.so.1 \
    vendor/google/taimen/proprietary/vendor/lib/dsp/geofence.napp_header:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/geofence.napp_header \
    vendor/google/taimen/proprietary/vendor/lib/dsp/gesture.napp_header:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/gesture.napp_header \
    vendor/google/taimen/proprietary/vendor/lib/dsp/imu_cal.napp_header:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/imu_cal.napp_header \
    vendor/google/taimen/proprietary/vendor/lib/dsp/mmecns_module.so.1:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/mmecns_module.so.1 \
    vendor/google/taimen/proprietary/vendor/lib/dsp/smartbatching.napp_header:$(TARGET_COPY_OUT_VENDOR)/lib/dsp/smartbatching.napp_header \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/APAC/Reliance/Commercial/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/APAC/Reliance/Commercial/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/AUS/Default/VoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/AUS/Default/VoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/AUS/Telstra/VoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/AUS/Telstra/VoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/EU/DT/VoLTE/Commercial/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/EU/DT/VoLTE/Commercial/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/EU/EE/Commercial/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/EU/EE/Commercial/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/EU/H3G/VoLTE/UK/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/EU/H3G/VoLTE/UK/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/EU/ID/Non_VoLTE/UK/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/EU/ID/Non_VoLTE/UK/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/EU/Telefonica/Commercial/DE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/EU/Telefonica/Commercial/DE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/EU/Telefonica/Non_VoLTE/UK/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/EU/Telefonica/Non_VoLTE/UK/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/EU/Vodafone/Lab/VoLTE/Germany/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/EU/Vodafone/Lab/VoLTE/Germany/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/EU/Vodafone/VoLTE/Germany/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/EU/Vodafone/VoLTE/Germany/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/EU/Vodafone/VoLTE/UK/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/EU/Vodafone/VoLTE/UK/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/ATT/VoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/ATT/VoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/Bell/VoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/Bell/VoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/Cricket/VoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/Cricket/VoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/Freedom/VoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/Freedom/VoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/Koodo/non_VoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/Koodo/non_VoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/ROGERS/Commercial/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/ROGERS/Commercial/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/Sprint/Commercial/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/Sprint/Commercial/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/TMO/Commercial/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/TMO/Commercial/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/Telus/VoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/Telus/VoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/USCC/Commercial/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/USCC/Commercial/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/Verizon/hVoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/Verizon/hVoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/NA/Videotron/non_VoLTE/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/NA/Videotron/non_VoLTE/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/common/PixelLite/Commercial/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/common/PixelLite/Commercial/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/generic/common/WildCard/WildCard/mcfg_sw.mbn:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/generic/common/WildCard/WildCard/mcfg_sw.mbn \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/mbn.ver:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/mbn.ver \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/mbn_sw.dig:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/mbn_sw.dig \
    vendor/google/taimen/proprietary/vendor/mbn/mcfg/configs/mcfg_sw/oem_sw.txt:$(TARGET_COPY_OUT_VENDOR)/mbn/mcfg/configs/mcfg_sw/oem_sw.txt \
    vendor/google/taimen/proprietary/vendor/media/LMspeed_508.emd:$(TARGET_COPY_OUT_VENDOR)/media/LMspeed_508.emd \
    vendor/google/taimen/proprietary/vendor/media/PFFprec_600.emd:$(TARGET_COPY_OUT_VENDOR)/media/PFFprec_600.emd \
    vendor/google/taimen/proprietary/vendor/media/ensemble_fd_model.emd:$(TARGET_COPY_OUT_VENDOR)/media/ensemble_fd_model.emd \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/10_israel_normal_ecc.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_israel_normal_ecc.sql \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/3_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_add_wps_config.sql \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/4_att_mcc_mnc_for_wps.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_att_mcc_mnc_for_wps.sql \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/5_recheck_ecc_setting.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_recheck_ecc_setting.sql \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/6_remove_unnecessary_entry.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_remove_unnecessary_entry.sql \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/7_singapore_ecc_995.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_singapore_ecc_995.sql \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/8_germany_ecc_110.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_germany_ecc_110.sql \
    vendor/google/taimen/proprietary/vendor/radio/qcril_database/upgrade/9_remove_germany_ecc_110.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_remove_germany_ecc_110.sql

PRODUCT_PACKAGES += \
    com.qualcomm.qti.ims.radio@1.0 \
    com.qualcomm.qti.ims.radio@1.1 \
    com.qualcomm.qti.imsrtpservice@1.0-service-Impl \
    com.qualcomm.qti.imsrtpservice@1.0_vendor \
    com.qualcomm.qti.qcril.qcrilhook@1.0 \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.server@1.0 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    activity_recognition.msm8998 \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    gatekeeper.msm8998 \
    sound_trigger.primary.msm8998 \
    vulkan.adreno \
    lib-dplmedia \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs \
    lib-imss \
    lib-imsxml \
    lib-rcsimssjni \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpdaemoninterface \
    lib-rtpsl \
    libC2D2 \
    libCB \
    libGPTEE \
    libGPreqcancel_svc \
    libQSEEComAPI \
    lib_aion_buffer \
    libacdb-fts \
    libacdbloader \
    libacdbmapper \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libaudcal \
    libaudioalsa \
    libbccQTI \
    libc2d30_bltlib \
    libcne \
    libcneapiclient \
    libcneqmiutils \
    libconfigdb \
    libdiag \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libeaselcomm \
    libeaselcontrol.amber \
    libelmyra-protos \
    libflp \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgeofence \
    libgnsspps \
    libgoog_llv_gpu \
    libgoog_zoom_core \
    libgpustats \
    libgsl \
    libhdrplusclientimpl \
    libhdrplusmessenger \
    libidl \
    libizat_core \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    liblistensoundmodel2 \
    libllvm-glnext \
    libllvm-qcom \
    libloc_api_v02 \
    libloc_ds_api \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libmdmdetect \
    libmdsprpc \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmulawdec \
    libnetmgr \
    libpdmapper \
    libperipheral_client \
    libqcci_legacy \
    libqcmaputils \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqmiservices_ext \
    libqmiservices_htc \
    libqseed3 \
    libqti-perfd-client \
    libquipc_os_api \
    libril-qc-ltedirectdisc \
    libril-qc-qmi-1 \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librmp \
    librpmb \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-apis \
    libsdmextension \
    libsdsprpc \
    libsensor1 \
    libsensor_reg \
    libsettings \
    libsmemlog \
    libsns_low_lat_stream_stub \
    libssd \
    libsystem_health_mon \
    libtime_genoff \
    libvoice-svc \
    libwms \
    libxml \
    sensors.msm8998 \
    vendor.qti.qcril.am@1.0 \
    libhalide_hexagon_remote_skel \
    activity \
    cc \
    chre_drv_loc \
    chre_drv_modem \
    chre_drv_wifi \
    chre_pal \
    elmyra \
    geofence \
    gesture \
    imu_cal \
    libchre_slpi_skel \
    lowi_client \
    smartbatching \
    sensors.vl530l0.tof \
    libactuator_lc898214xd \
    libadm \
    libadpcmdec \
    libchromatix_imx179_pixel_common \
    libchromatix_imx179_pixel_postproc \
    libchromatix_imx179_pixel_res0_snapshot_3a \
    libchromatix_imx179_pixel_res0_snapshot_cpp \
    libchromatix_imx179_pixel_res0_snapshot_isp \
    libchromatix_imx179_pixel_res1_video_30_3a \
    libchromatix_imx179_pixel_res1_video_30_cpp \
    libchromatix_imx179_pixel_res1_video_30_isp \
    libchromatix_imx179_pixel_res2_video_qtr_3a \
    libchromatix_imx179_pixel_res2_video_qtr_cpp \
    libchromatix_imx179_pixel_res2_video_qtr_isp \
    libchromatix_imx362_pixel_common \
    libchromatix_imx362_pixel_postproc \
    libchromatix_imx362_pixel_res0_snapshot_3a \
    libchromatix_imx362_pixel_res0_snapshot_cpp \
    libchromatix_imx362_pixel_res0_snapshot_cpp_preview \
    libchromatix_imx362_pixel_res0_snapshot_isp \
    libchromatix_imx362_pixel_res0_snapshot_isp_preview \
    libchromatix_imx362_pixel_res1_video_30_3a \
    libchromatix_imx362_pixel_res1_video_30_cpp \
    libchromatix_imx362_pixel_res1_video_30_isp \
    libchromatix_imx362_pixel_res1_zzhdr_video_30_3a \
    libchromatix_imx362_pixel_res1_zzhdr_video_30_cpp \
    libchromatix_imx362_pixel_res1_zzhdr_video_30_isp \
    libchromatix_imx362_pixel_res2_video_60_3a \
    libchromatix_imx362_pixel_res2_video_60_cpp \
    libchromatix_imx362_pixel_res2_video_60_isp \
    libchromatix_imx362_pixel_res3_video_120_3a \
    libchromatix_imx362_pixel_res3_video_120_cpp \
    libchromatix_imx362_pixel_res3_video_120_isp \
    libchromatix_imx362_pixel_res4_video_240_3a \
    libchromatix_imx362_pixel_res4_video_240_cpp \
    libchromatix_imx362_pixel_res4_video_240_isp \
    libchromatix_imx362_pixel_res4_video_60_fullfov_3a \
    libchromatix_imx362_pixel_res4_video_60_fullfov_cpp \
    libchromatix_imx362_pixel_res4_video_60_fullfov_isp \
    libchromatix_imx362_pixel_res7_video_30_llv_3a \
    libchromatix_imx362_pixel_res7_video_30_llv_cpp \
    libchromatix_imx362_pixel_res7_video_30_llv_cpp_preview \
    libchromatix_imx362_pixel_res7_video_30_llv_isp \
    libchromatix_imx362_pixel_res7_video_30_llv_isp_preview \
    libchromatix_imx362_pixel_zzhdr_common \
    libcppf \
    libeglc2d \
    libfastcvopt \
    libflash_pmic \
    libgcam_ae \
    libgcam_ensemble \
    libgcam_frsdk \
    libgoog_eis_armeabi-v7a \
    libgoog_llv \
    libgoog_llv_plugin \
    libgoog_zoom \
    libgoog_zoom_crop \
    libhalide_hexagon_host \
    libhdrplusclient \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_FW_utils \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_imglib \
    libmmcamera_imx179 \
    libmmcamera_imx362 \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_ois_utils \
    libmmcamera_onsemi_lc898123f40xc_eeprom \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_primax_g802l_eeprom \
    libmmcamera_thread_services \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmotion_ae \
    liboemcrypto \
    libois_lc898123f40 \
    libpn553_fw \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libtracking_af \
    libwvhidl \
    libfmas \
    com.fingerprints.extension@1.0 \
    android.hardware.bluetooth@1.0-impl-qti \
    libSecureUILib \
    libStDrvInt \
    libbtnv \
    libhexagon_nn_controller \
    liboemlock-provision \
    liboemlock \
    librmnetctl \
    libsecureui_svcsock \
    libthermalioctl \
    libapps_mem_heap \
    libdspCV_skel \
    libexternal_dog_skel \
    libhexagon_nn_skel \
    libsns_low_lat_stream_skel \
    ModemService \
    QtiTelephonyService \
    TimeService \
    wahoo_gfxdrv \
    qti-vzw-ims-internal \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    KmInstallKeybox \
    PktRspTest \
    StoreKeybox \
    WifiLogger_app \
    adsprpcd \
    athdiag \
    cnd \
    cnss-daemon \
    cnss_diag \
    diag_callback_sample \
    diag_dci_sample \
    diag_klog \
    diag_mdlog \
    diag_socket_log \
    diag_uart_log \
    ese_load \
    ftmdaemon \
    android.hardware.biometrics.fingerprint@2.1-service.fpc \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    android.hardware.oemlock@1.0-service \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    loc_launcher \
    lowi-server \
    msm_irqbalance \
    netmgrd \
    nl_listener \
    oemlock-bridge \
    oemlock-bridge-client \
    oemlock_provision \
    pd-mapper \
    pktlogconf \
    pm-proxy \
    pm-service \
    port-bridge \
    qseecom_sample_client \
    qseecomd \
    qseeproxydaemon \
    qseeproxysampledaemon \
    qti \
    radish \
    ramoops \
    rmt_storage \
    sensors.qcom \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    test_diag \
    tftp_server \
    thermal-engine \
    time_daemon \
    xtra-daemon

PRODUCT_PACKAGES += \
    vendor_lib_eglSubDriverAndroid_so \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv1_CM_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib_libq3dtools_esx_so \
    vendor_lib64_eglSubDriverAndroid_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv1_CM_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so \
    vendor_lib64_libq3dtools_esx_so
